stages:
  - build
#  - deploy

variables:
  GIT_DEPTH: "3"

.job_template: &build_job
  type: build
  tags:
    - docker
  script:
    - scripts/build_gitlab/linux.sh

### BUILD JOBS ###

build-arch-gcc:
  <<: *build_job
  image: jeffamstutz/docker-autobuild:latest

build-ubuntu-gcc:
  <<: *build_job
  image: jeffamstutz/docker-autobuild:ubuntu
