stages:
  - build
#  - deploy

variables:
  GIT_DEPTH: "3"

.job_template: &build_job_docker
  type: build
  tags:
    - docker
  image: ospray/docker-images:arch  # default image
  script:
    - scripts/build_gitlab/linux.sh # default script

### BUILD JOBS ###

build-arch-gcc:
  <<: *build_job_docker

build-arch-clang:
  <<: *build_job_docker
  script:
    - export CC=clang
    - export CXX=clang++
    - scripts/build_gitlab/linux.sh

build-ubuntu1604-gcc:
  <<: *build_job_docker
  image: ospray/docker-images:ubuntu16.04

build-centos6-gcc:
  <<: *build_job_docker
  image: ospray/docker-images:centos6

build-centos7-gcc:
  <<: *build_job_docker
  image: ospray/docker-images:centos7

build-debug:
  <<: *build_job_docker
  script:
    - scripts/build_gitlab/linux.sh -DCMAKE_BUILD_TYPE=Debug

build-mpi:
  <<: *build_job_docker
  script:
    - scripts/build_gitlab/linux.sh -DOSPRAY_MODULE_MPI=ON
