stages:
  - build
  - deploy

### BUILD JOBS ###

build-centos6-gcc:
  type: build
  script:
    - scripts/build_gitlab/linux.sh
  tags:
    - centos6
    - gcc
    - build

build-centos7-gcc:
  type: build
  script:
    - scripts/build_gitlab/linux.sh
  tags:
    - centos7
    - gcc
    - build

build-fedora-gcc:
  type: build
  script:
    - scripts/build_gitlab/linux.sh
  tags:
    - fedora
    - gcc
    - build

build-ubuntu-gcc:
  type: build
  script:
    - scripts/build_gitlab/linux.sh
  tags:
    - ubuntu
    - gcc
    - build

#build-ubuntu-clang:
#  type: build
#  script:
#    - export CC=clang
#    - export CXX=clang++
#    - scripts/build_gitlab/linux.sh
#  tags:
#    - ubuntu
#    - clang

build-sles-gcc:
  type: build
  script:
    - scripts/build_gitlab/linux.sh
  tags:
    - sles
    - gcc
    - build

build-osx-clang:
  type: build
  script:
    - scripts/build_gitlab/osx.sh
  tags:
    - osx
    - clang
    - build

build-windows-msvc:
  type: build
  script:
    - call scripts\build_gitlab\win.bat
  tags:
    - msvc
    - build

### RELEASE JOBS ###

release-linux-gcc:
  type: deploy
  script:
    - module load gcc
    - export CC=gcc
    - export CXX=g++
    - export OSPRAY_RELEASE_NO_VERIFY=1
    - scripts/release/linux.sh
  tags:
    - gcc
    - release
  only:
    - devel
    - master
  artifacts:
    paths:
      - build_release/*.gz

release-linux-icc:
  type: deploy
  script:
    - module load intel
    - export CC=icc
    - export CXX=icpc
    - scripts/release/linux.sh
  tags:
    - icc
    - release
  only:
    - devel
    - master
  artifacts:
    paths:
      - build_release/*.gz

release-windows:
  type: deploy
  script:
    - call scripts\release\win.bat
  tags:
    - msvc
    - release
  only:
    - devel
    - master
  artifacts:
    paths:
      - build_release\ospray*.zip
      - build_release\ospray*.exe

#TODO: add OS X release jobs
